### ISSUE TITLE
pypy 5.7 doesn't like unicode in __import__() in template/utils.py

### ISSUE THREAD

**Issue by AndreCimander** [nyaruka/django-hamlpy#70]
Hey,

I just noticed that our pypy'd celery workers won't start with django-hamlpy under pypy 5.7 for python 2.7.

I removed unicode_literals import as a quickfix, might be a PyPy/future bug.

```
Traceback (most recent call last):
  File "manage.py", line 49, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/idb/www/apps/worker4/envpypy/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/idb/www/apps/worker4/envpypy/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/idb/www/apps/worker4/envpypy/site-packages/djcelery/management/commands/celery.py", line 21, in run_from_argv
    ['{0[0]} {0[1]}'.format(argv)] + argv[2:],
  File "/usr/idb/www/apps/worker4/envpypy/site-packages/celery/bin/celery.py", line 793, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/idb/www/apps/worker4/envpypy/site-packages/celery/bin/base.py", line 311, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/idb/www/apps/worker4/envpypy/site-packages/celery/bin/celery.py", line 785, in handle_argv
    return self.execute(command, argv)
  File "/usr/idb/www/apps/worker4/envpypy/site-packages/celery/bin/celery.py", line 717, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/usr/idb/www/apps/worker4/envpypy/site-packages/celery/bin/worker.py", line 179, in run_from_argv
    return self(*args, **options)
  File "/usr/idb/www/apps/worker4/envpypy/site-packages/celery/bin/base.py", line 274, in __call__
    ret = self.run(*args, **kwargs)
  File "/usr/idb/www/apps/worker4/envpypy/site-packages/celery/bin/worker.py", line 212, in run
    state_db=self.node_format(state_db, hostname), **kwargs
  File "/usr/idb/www/apps/worker4/envpypy/site-packages/celery/worker/__init__.py", line 95, in __init__
    self.app.loader.init_worker()
  File "/usr/idb/www/apps/worker4/envpypy/site-packages/celery/loaders/base.py", line 128, in init_worker
    self.import_default_modules()
  File "/usr/idb/www/apps/worker4/envpypy/site-packages/celery/loaders/base.py", line 116, in import_default_modules
    signals.import_modules.send(sender=self.app)
  File "/usr/idb/www/apps/worker4/envpypy/site-packages/celery/utils/dispatch/signal.py", line 166, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/idb/www/apps/worker4/envpypy/site-packages/celery/fixups/django.py", line 73, in on_import_modules
    self.worker_fixup.validate_models()
  File "/usr/idb/www/apps/worker4/envpypy/site-packages/celery/fixups/django.py", line 173, in validate_models
    cmd.check()
  File "/usr/idb/www/apps/worker4/envpypy/site-packages/django/core/management/base.py", line 426, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/idb/www/apps/worker4/envpypy/site-packages/django/core/checks/registry.py", line 75, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/idb/www/apps/worker4/envpypy/site-packages/admin_tools/checks.py", line 18, in check_admin_tools_configuration
    get_template('admin:admin/base.html')
  File "/usr/idb/www/apps/worker4/envpypy/site-packages/django/template/loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "/usr/idb/www/apps/worker4/envpypy/site-packages/django/template/backends/django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "/usr/idb/www/apps/worker4/envpypy/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/usr/idb/www/apps/worker4/envpypy/site-packages/django/template/engine.py", line 153, in find_template
    for loader in self.template_loaders:
  File "/usr/idb/www/apps/worker4/envpypy/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/idb/www/apps/worker4/envpypy/site-packages/django/template/engine.py", line 118, in template_loaders
    return self.get_template_loaders(self.loaders)
  File "/usr/idb/www/apps/worker4/envpypy/site-packages/django/template/engine.py", line 123, in get_template_loaders
    loader = self.find_template_loader(template_loader)
  File "/usr/idb/www/apps/worker4/envpypy/site-packages/django/template/engine.py", line 146, in find_template_loader
    return loader_class(*args)
  File "/usr/idb/www/apps/worker4/envpypy/site-packages/django/template/loaders/cached.py", line 24, in __init__
    self.loaders = engine.get_template_loaders(loaders)
  File "/usr/idb/www/apps/worker4/envpypy/site-packages/django/template/engine.py", line 123, in get_template_loaders
    loader = self.find_template_loader(template_loader)
  File "/usr/idb/www/apps/worker4/envpypy/site-packages/django/template/engine.py", line 136, in find_template_loader
    loader_class = import_string(loader)
  File "/usr/idb/www/apps/worker4/envpypy/site-packages/django/utils/module_loading.py", line 20, in import_string
    module = import_module(module_path)
  File "/usr/idb/www/apps/worker4/pypy/pypy/lib-python/2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/idb/www/apps/worker4/envpypy/site-packages/hamlpy/template/__init__.py", line 6, in <module>
    from .loaders import haml_loaders as _loaders
  File "/usr/idb/www/apps/worker4/envpypy/site-packages/hamlpy/template/loaders.py", line 68, in <module>
    haml_loaders = dict((name, get_haml_loader(loader)) for (name, loader) in get_django_template_loaders())
  File "/usr/idb/www/apps/worker4/envpypy/site-packages/hamlpy/template/utils.py", line 14, in get_django_template_loaders
    for loader in get_submodules(loaders) if hasattr(loader, 'Loader')]
  File "/usr/idb/www/apps/worker4/envpypy/site-packages/hamlpy/template/utils.py", line 19, in get_submodules
    return [__import__(module, {}, {}, [module.rsplit(".", 1)[-1]]) for module in submodules]
TypeError: 'fromlist' items must be str, not unicode
```

**Comment by AndreCimander** [comment]
never mind, it's a PyPy bug: https://bitbucket.org/pypy/pypy/issues/2524/regression-__import__-does-not-allow

Sorry for bothering! :smile:

**Comment by rowanseymour** [comment]
Np. I'd be ok with putting `str(..)` in there if you need a workaround.
